# Comprehensions em Python

In [3]:
'''
Comprehensions fornecem uma forma concisa de criar coleções. 
Elas podem ser usadas para realizar diversas operações, como filtragem, 
transformação, ou combinação de elementos.
''';

### List Comprehensions

In [1]:
# Criando uma lista dos quadrados dos números
numeros = [1, 2, 3, 4, 5]
quadrados = [n**2 for n in numeros]
print(quadrados)  # [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


### Dict Comprehensions

In [5]:
# Criando um dicionário com números e seus quadrados
numeros = [1, 2, 3, 4, 5]
dicionario_quadrados = {i: n**2 for i, n in enumerate(numeros)}
print(dicionario_quadrados)  # {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

{0: 1, 1: 4, 2: 9, 3: 16, 4: 25}


# Módulos e Pacotes em Python

In [10]:
'''
Módulos são arquivos Python que contêm conjuntos de funções, classes e variáveis relacionadas. 
Eles são uma maneira de organizar o código de maneira modular e reutilizável. 
Um arquivo Python é tratado como um módulo quando você o importa usando a palavra-chave import.
'''

# Principais formas de importar módulos
import numpy # Importar biblioteca completa
import numpy as np # Importar biblioteca completa só que se referenciar a ela por um nome diferente
from numpy import array # Importar apenas uma funcionalidade específica de um módulo

a = numpy.array([10, 20, 30])
b = np.array([1, 2, 3])
c = array([4, 5, 6])

print(a)
print(b)
print(c)

[10 20 30]
[1 2 3]
[4 5 6]


# Classes

In [12]:
from IPython.display import Markdown, display # Utilizando display e Markdown para formatação(neste caso, deixar o texto em negrito, quebra de -
# linha, etc)
import random

random.seed(42)

class Aluno: # O início de declaração de uma classe se assemelha a outras estruturas de contrule de fluxo, mas aqui é de controle de estrutura
  ultimo_RA = 0 # Variáveis declaradas dentro da classe são acessíveis e globais a todos os elementos do tipo da classe

  def __init__(self, nome): # A função __init__(self, parametros) é uma função "mágica" que sempre quando declarada numa classe, inicializa -
# cada objeto do tipo da classe
    self.nome = nome # self referencia o objeto que está sendo inicializado. A partir desta palavra chave é possível inicializar os atributos -
# dos objetos do tipo da classe no momento de sua criação.
    Aluno.ultimo_RA+=1 # Para acessar variáveis que são globais a todos objetos daquela classe, é necessário referênciar o nome da classe.
    self.RA = Aluno.ultimo_RA
    self.IRA = 20000
    self.historico = {}

  def finalizar_disciplina(self, disciplina, nota, frequencia): # Objetos de uma classe podem ter suas próprias funções especiais.
    # Estas funções especiais, quase são referentes a um objeto específico daquela classe, devem incluir a palavra chave "self".
    # Ela permite acessar as informações e outras funções daquela instância da classe.
    self.historico[disciplina] = {'nota' : nota, 'frequencia' : frequencia}

  def exibir_historico(self):
    display(Markdown(f'Nome do Aluno: **{self.nome}**. RA: **{self.RA}**'))
    for disciplina, avaliacao in self.historico.items():
      display(Markdown(f'''* {disciplina}: nota - **{avaliacao["nota"]:.2f}**. frequência - **{avaliacao["frequencia"]:.0%}**. **{"APROVADO"
       if avaliacao["nota"] >= 6.0 and avaliacao["frequencia"] >= 0.8 else "REPROVADO"}**'''))

lista_alunos = [
    Aluno('Amanda'),
    Aluno('Xavier'),
    Aluno('Vinícius'),
    Aluno('Fabiano')
]

display(Markdown('<br>**Acessando o nome de cada aluno:**'), [aluno.nome for aluno in lista_alunos])
display(Markdown('<br>**Acessando o nome e o RA de cada aluno:**'), [(aluno.nome, aluno.RA) for aluno in lista_alunos])

display(Markdown('<br>**Agora exibindo o histórico de cada aluno:**'))
[aluno.exibir_historico() for aluno in lista_alunos]

[aluno.finalizar_disciplina('catalogação 3', random.uniform(5.5, 10.0), random.uniform(0.6, 1.0)) for aluno in lista_alunos]

display(Markdown('<br>**Exibindo novamente o histórico de cada aluno após finalizarmos a disciplina de catalogação 3:**'))
[aluno.exibir_historico() for aluno in lista_alunos];

lista_disciplinas = [
    "cálculo 2",
    "compiladores",
    "libras"
]

[[aluno.finalizar_disciplina(disciplina, random.uniform(5.5, 10.0), random.uniform(0.6, 1.0))
  for disciplina in lista_disciplinas]
    for aluno in lista_alunos];

display(Markdown('<br>**Exibindo novamente o histórico de cada aluno após finalizarmos as outras disciplinas:**'))
[aluno.exibir_historico() for aluno in lista_alunos];

<br>**Acessando o nome de cada aluno:**

['Amanda', 'Xavier', 'Vinícius', 'Fabiano']

<br>**Acessando o nome e o RA de cada aluno:**

[('Amanda', 1), ('Xavier', 2), ('Vinícius', 3), ('Fabiano', 4)]

<br>**Agora exibindo o histórico de cada aluno:**

Nome do Aluno: **Amanda**. RA: **1**

Nome do Aluno: **Xavier**. RA: **2**

Nome do Aluno: **Vinícius**. RA: **3**

Nome do Aluno: **Fabiano**. RA: **4**

<br>**Exibindo novamente o histórico de cada aluno após finalizarmos a disciplina de catalogação 3:**

Nome do Aluno: **Amanda**. RA: **1**

* catalogação 3: nota - **8.38**. frequência - **61%**. **REPROVADO**

Nome do Aluno: **Xavier**. RA: **2**

* catalogação 3: nota - **6.74**. frequência - **69%**. **REPROVADO**

Nome do Aluno: **Vinícius**. RA: **3**

* catalogação 3: nota - **8.81**. frequência - **87%**. **APROVADO**

Nome do Aluno: **Fabiano**. RA: **4**

* catalogação 3: nota - **9.51**. frequência - **63%**. **REPROVADO**

<br>**Exibindo novamente o histórico de cada aluno após finalizarmos as outras disciplinas:**

Nome do Aluno: **Amanda**. RA: **1**

* catalogação 3: nota - **8.38**. frequência - **61%**. **REPROVADO**

* cálculo 2: nota - **7.40**. frequência - **61%**. **REPROVADO**

* compiladores: nota - **6.48**. frequência - **80%**. **APROVADO**

* libras: nota - **5.62**. frequência - **68%**. **REPROVADO**

Nome do Aluno: **Xavier**. RA: **2**

* catalogação 3: nota - **6.74**. frequência - **69%**. **REPROVADO**

* cálculo 2: nota - **8.42**. frequência - **82%**. **APROVADO**

* compiladores: nota - **6.49**. frequência - **84%**. **APROVADO**

* libras: nota - **9.14**. frequência - **60%**. **REPROVADO**

Nome do Aluno: **Vinícius**. RA: **3**

* catalogação 3: nota - **8.81**. frequência - **87%**. **APROVADO**

* cálculo 2: nota - **9.13**. frequência - **88%**. **APROVADO**

* compiladores: nota - **7.03**. frequência - **66%**. **REPROVADO**

* libras: nota - **9.81**. frequência - **73%**. **REPROVADO**

Nome do Aluno: **Fabiano**. RA: **4**

* catalogação 3: nota - **9.51**. frequência - **63%**. **REPROVADO**

* cálculo 2: nota - **5.92**. frequência - **64%**. **REPROVADO**

* compiladores: nota - **9.31**. frequência - **84%**. **APROVADO**

* libras: nota - **9.13**. frequência - **89%**. **APROVADO**